/**
 * Authservice
 * Authservice.io provides Authentication and Authorisation services for web based applications. It can also maintain user profile information, relationship between users, and assist with communicating with users by email and SMS. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@authservice.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApikeyloginauthorityManufacturer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApikeyloginauthorityManufacturer'));
  } else {
    // Browser globals (root is window)
    if (!root.Authservice) {
      root.Authservice = {};
    }
    root.Authservice.InlineResponse2001 = factory(root.Authservice.ApiClient, root.Authservice.ApikeyloginauthorityManufacturer);
  }
}(this, function(ApiClient, ApikeyloginauthorityManufacturer) {
  'use strict';




  /**
   * The InlineResponse2001 model module.
   * @module model/InlineResponse2001
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2001</code>.
   * @alias module:model/InlineResponse2001
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param releaseDate {String} 
   */
  var exports = function(id, name, releaseDate) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['releaseDate'] = releaseDate;

  };

  /**
   * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('releaseDate')) {
        obj['releaseDate'] = ApiClient.convertToType(data['releaseDate'], 'String');
      }
      if (data.hasOwnProperty('manufacturer')) {
        obj['manufacturer'] = ApikeyloginauthorityManufacturer.constructFromObject(data['manufacturer']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} releaseDate
   */
  exports.prototype['releaseDate'] = undefined;
  /**
   * @member {module:model/ApikeyloginauthorityManufacturer} manufacturer
   */
  exports.prototype['manufacturer'] = undefined;



  return exports;
}));


