/**
 * Authservice
 * Authservice.io provides Authentication and Authorisation services for web based applications. It can also maintain user profile information, relationship between users, and assist with communicating with users by email and SMS. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@authservice.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApikeyloginauthorityManufacturer', 'model/HealthcheckFail', 'model/HealthcheckOk', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse200Database', 'model/InlineResponse406', 'model/InlineResponse406Cache', 'model/InlineResponse406Database', 'model/InventoryItem', 'model/Manufacturer', 'api/AdminApi', 'api/LoginApi', 'api/Not_hereApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApikeyloginauthorityManufacturer'), require('./model/HealthcheckFail'), require('./model/HealthcheckOk'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse200Database'), require('./model/InlineResponse406'), require('./model/InlineResponse406Cache'), require('./model/InlineResponse406Database'), require('./model/InventoryItem'), require('./model/Manufacturer'), require('./api/AdminApi'), require('./api/LoginApi'), require('./api/Not_hereApi'));
  }
}(function(ApiClient, ApikeyloginauthorityManufacturer, HealthcheckFail, HealthcheckOk, InlineResponse200, InlineResponse2001, InlineResponse200Database, InlineResponse406, InlineResponse406Cache, InlineResponse406Database, InventoryItem, Manufacturer, AdminApi, LoginApi, Not_hereApi) {
  'use strict';

  /**
   * Authservice_io_provides_Authentication_and_Authorisation_servicesfor_web_based_applications__It_can_also_maintain_user_profile_informationrelationship_between_users_and_assist_with_communicating_with_users_byemail_and_SMS_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Authservice = require('index'); // See note below*.
   * var xxxSvc = new Authservice.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Authservice.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Authservice.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Authservice.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApikeyloginauthorityManufacturer model constructor.
     * @property {module:model/ApikeyloginauthorityManufacturer}
     */
    ApikeyloginauthorityManufacturer: ApikeyloginauthorityManufacturer,
    /**
     * The HealthcheckFail model constructor.
     * @property {module:model/HealthcheckFail}
     */
    HealthcheckFail: HealthcheckFail,
    /**
     * The HealthcheckOk model constructor.
     * @property {module:model/HealthcheckOk}
     */
    HealthcheckOk: HealthcheckOk,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse200Database model constructor.
     * @property {module:model/InlineResponse200Database}
     */
    InlineResponse200Database: InlineResponse200Database,
    /**
     * The InlineResponse406 model constructor.
     * @property {module:model/InlineResponse406}
     */
    InlineResponse406: InlineResponse406,
    /**
     * The InlineResponse406Cache model constructor.
     * @property {module:model/InlineResponse406Cache}
     */
    InlineResponse406Cache: InlineResponse406Cache,
    /**
     * The InlineResponse406Database model constructor.
     * @property {module:model/InlineResponse406Database}
     */
    InlineResponse406Database: InlineResponse406Database,
    /**
     * The InventoryItem model constructor.
     * @property {module:model/InventoryItem}
     */
    InventoryItem: InventoryItem,
    /**
     * The Manufacturer model constructor.
     * @property {module:model/Manufacturer}
     */
    Manufacturer: Manufacturer,
    /**
     * The AdminApi service constructor.
     * @property {module:api/AdminApi}
     */
    AdminApi: AdminApi,
    /**
     * The LoginApi service constructor.
     * @property {module:api/LoginApi}
     */
    LoginApi: LoginApi,
    /**
     * The Not_hereApi service constructor.
     * @property {module:api/Not_hereApi}
     */
    Not_hereApi: Not_hereApi
  };

  return exports;
}));
